# -*- coding: utf-8 -*-
#
# This file is part of Invenio
# Copyright (C) 2015, 2016 CERN
#
# Invenio is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

addons:
  postgresql: 9.3

notifications:
  email: false

sudo: false

language: python

cache:
  - pip

services:
  - docker

env:
  global:
    - DOCKER_VERSION=1.12.3-0~trusty
    - DOCKER_COMPOSE_VERSION=1.9.0
  matrix:
    - SUITE=py27
      # this ^ suite includes the pep8, packaging, docs, doctests, docstyle
      # and py27 tox environment runs
    - SUITE=py27mysql
    - SUITE=py27postgres

    - SUITE=py35
    - SUITE=py35mysql
    - SUITE=py35postgres

before_install:
  - "travis_retry pip install --upgrade pip setuptools coveralls"
# FIXME: span also all the requirement levels in the matrix
#  - "requirements-builder -e all --level=min setup.py > .travis-lowest-requirements.txt"
#  - "requirements-builder -e all --level=pypi setup.py > .travis-release-requirements.txt"
#  - "requirements-builder -e all --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"
  # List available docker versions.
  - apt-cache madison docker-engine
  # Update Docker to 1.10.1 https://graysonkoonce.com/managing-docker-and-docker-compose-versions-on-travis-ci/.
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y "docker-engine=${DOCKER_VERSION}"
  # Add docker-compose at the version specified in ENV.
  - sudo rm /usr/local/bin/docker-compose
  - curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - pip install --upgrade pip setuptools
  - pip install "autosemver>=0.1.9"
  - autosemver . version
  - autosemver . changelog

install:
  - "travis_retry docker-compose -f docker-compose.tests.yaml pull"
  - "travis_retry docker-compose -f docker-compose.tests.yaml build test-$SUITE"

script:
  - docker-compose -f docker-compose.tests.yaml run --rm "test-$SUITE"

after_script:
  - "docker-compose -f docker-compose.tests.yaml kill"
  - "docker-compose -f docker-compose.tests.yaml rm -f"

after_success:
  # Coverage report contains Docker paths. We replace them, so that we can run Coveralls.
  - sed -i 's@\"/code/@'"\"$(pwd)/"'@g' .coverage
  - coveralls
  - sudo git clean -fdx
  - sudo rm -rf .cache .tox .eggs

deploy:
  provider: pypi
  user: jirikuncar
  password:
    secure: lD3uH3wJi/i+wCV/tHUA7i4FvGZ2LzDtMmSphjht9FmTnO+CiKAgNG9BvtGa9ofvX/wK/Dl97ipAQcY30tSTtEbxZF9XSKJA82xjpWZY92vqgbKIio5ZkDuZfxTRsY9L+pSjswptRcZ7AHQdpbiyKHwS51wP4GwA2GTtW2/VXxLiyKL7RHtrzTOARpgmGEd1+EB5oPrsWN0gfR0bxqyWgIvYBD4MEkUvZb31OuKq/opVTDvW+NrZfC/K19TbULbBmAK4jUnv3z1ushCCq47241Vg457zhdr7nn0gsbwuvY+vSdKBvSMp53iElovVU3KsR0k24SS1cfpVnYTKjhEKpDHmBaIBiMZG2YXgzCTNB5V3+cQNPJHtsLdFHMlnigtIPx0af71wQtMd/I4B/wD9Uy3u+n8/c06XLgn5M1aoUWbQ9TyeJ4ZQUrh7aFtXPxOMbJpvBBnIK1GOIMEz2WMEmqRBsA5tIZiCdc8IGOklAC19+9h7tyKziCZcgmlGI6LwQiwEDwn20vTJkpli6VYObeM0vBsTW0TuU/m9SmA4efvsxLcMFOUl6d+k0ORlK/If/lgJ2ionybd5/rtMb6YpyuoVxgz/QRn/q0Urr778ydLPTonXZsobKDFtH3l8LPlRlOxNuVzphjlTgVl0AIfNicpiQyUTvckNPun9NLVXqaw=
  distributions: "sdist"
  on:
    python: "2.7"
